[phases.setup]
nixPkgs = ["python310", "ffmpeg"]

[phases.install]
cmds = ["python3.10 -m pip install --upgrade pip", "python3.10 -m pip install -r requirements.txt"]

[start]
cmd = "python3.10 -m uvicorn src.main:app --host 0.0.0.0 --port $PORT"
